server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local_qa}
---
spring:
  config:
    activate:
      on-profile: local_qa
  datasource:
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USER}
    password: ${DB_DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
jwt:
  secret: mySuperSecretKey987

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USER}
    password: ${DB_PROD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: mySuperSecretKey987